name: Step 2, Find a commit in history

# This step listens for the learner creating or editing an issue comment.
# This workflow updates from step 2 to step 3.

# This will run every time we create or edit an issue comment.
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited]

permissions:
  # Need `contents: read` to checkout the repository.
  # Need `contents: write` to update the step metadata.
  contents: write

jobs:
  # Get the current step to only run the main job when the learner is on the same step.
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
      - id: get_commit_id
        run: |
          echo "commit_id=$(cat ./.github/files/SIDEBARCOMMIT)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}
      commit_id: ${{ steps.get_commit_id.outputs.commit_id }}

  on_fix_the_sidebar_issue_comment:
    name: Check if the issue comment is referencing the correct commit ID
    needs: get_current_step

    # We will only run this action when:
    # 1. This repository isn't the template repository.
    # 2. The step is currently 2.
    # Reference: https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference: https://docs.github.com/en/actions/learn-github-actions/expressions
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 2 }}

    # We'll run Ubuntu for performance instead of Mac or Windows.
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Let's get all the branches.

      - name: Dump GitHub comment context
        id: github_comment_step
        env:
          COMMENT_CONTEXT: ${{ toJSON(github.event.comment) }}
        run: echo "$COMMENT_CONTEXT"

      - name: Dump GitHub issue context
        id: github_issue_step
        env:
          ISSUE_CONTEXT: ${{ toJSON(github.event.issue) }}
        run: echo "$ISSUE_CONTEXT"

      - name: Check if the issue comment is referencing the required commit ID
        if: contains(github.event.comment.body, needs.get_current_step.outputs.commit_id)
        run: echo 'Found the reference to required commit in the comment'

      # Update README from step 2 to step 3.
      - name: Update to step 3
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 2
          to_step: 3
